// auth
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// Project
export const GET_SAMPLE_PROJECT = "GET_SAMPLE_PROJECT";
export const GET_SAMPLE_PROJECT_SUCCESS = "GET_SAMPLE_PROJECT_SUCCESS";
export const GET_SAMPLE_PROJECT_FAIL = "GET_SAMPLE_PROJECT_FAIL";

export const POST_SAMPLE_PROJECT = "POST_SAMPLE_PROJECT";
export const POST_SAMPLE_PROJECT_SUCCESS = "POST_SAMPLE_PROJECT_SUCCESS";
export const POST_SAMPLE_PROJECT_FAIL = "POST_SAMPLE_PROJECT_FAIL";

export const PUT_SAMPLE_PROJECT = "PUT_SAMPLE_PROJECT";
export const PUT_SAMPLE_PROJECT_SUCCESS = "PUT_SAMPLE_PROJECT_SUCCESS";
export const PUT_SAMPLE_PROJECT_FAIL = "PUT_SAMPLE_PROJECT_FAIL";

export const DELETE_SAMPLE_PROJECT = "DELETE_SAMPLE_PROJECT";
export const DELETE_SAMPLE_PROJECT_SUCCESS = "DELETE_SAMPLE_PROJECT_SUCCESS";
export const DELETE_SAMPLE_PROJECT_FAIL = "DELETE_SAMPLE_PROJECT_FAIL";

// Phase
export const GET_PHASE = "GET_PHASE";
export const GET_PHASE_SUCCESS = "GET_PHASE_SUCCESS";
export const GET_PHASE_FAIL = "GET_PHASE_FAIL";

export const POST_PHASE = "POST_PHASE";
export const POST_PHASE_SUCCESS = "POST_PHASE_SUCCESS";
export const POST_PHASE_FAIL = "POST_PHASE_FAIL";

export const PUT_PHASE = "PUT_PHASE";
export const PUT_PHASE_SUCCESS = "PUT_PHASE_SUCCESS";
export const PUT_PHASE_FAIL = "PUT_PHASE_FAIL";

export const DELETE_PHASE = "DELETE_PHASE";
export const DELETE_PHASE_SUCCESS = "DELETE_PHASE_SUCCESS";
export const DELETE_PHASE_FAIL = "DELETE_PHASE_FAIL";

// Task
export const GET_TASK = "GET_TASK";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAIL = "GET_TASK_FAIL";

export const POST_TASK = "POST_TASK";
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export const POST_TASK_FAIL = "POST_TASK_FAIL";

export const PUT_TASK = "PUT_TASK";
export const PUT_TASK_SUCCESS = "PUT_TASK_SUCCESS";
export const PUT_TASK_FAIL = "PUT_TASK_FAIL";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

// Material
export const GET_MATERIAL = "GET_MATERIAL";
export const GET_MATERIAL_SUCCESS = "GET_MATERIAL_SUCCESS";
export const GET_MATERIAL_FAIL = "GET_MATERIAL_FAIL";

export const POST_MATERIAL = "POST_MATERIAL";
export const POST_MATERIAL_SUCCESS = "POST_MATERIAL_SUCCESS";
export const POST_MATERIAL_FAIL = "POST_MATERIAL_FAIL";

export const PUT_MATERIAL = "PUT_MATERIAL";
export const PUT_MATERIAL_SUCCESS = "PUT_MATERIAL_SUCCESS";
export const PUT_MATERIAL_FAIL = "PUT_MATERIAL_FAIL";

export const DELETE_MATERIAL = "DELETE_MATERIAL";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";
export const DELETE_MATERIAL_FAIL = "DELETE_MATERIAL_FAIL";

// Measurement
export const GET_MEASUREMENT = "GET_MEASUREMENT";
export const GET_MEASUREMENT_SUCCESS = "GET_MEASUREMENT_SUCCESS";
export const GET_MEASUREMENT_FAIL = "GET_MEASUREMENT_FAIL";

export const POST_MEASUREMENT = "POST_MEASUREMENT";
export const POST_MEASUREMENT_SUCCESS = "POST_MEASUREMENT_SUCCESS";
export const POST_MEASUREMENT_FAIL = "POST_MEASUREMENT_FAIL";

export const PUT_MEASUREMENT = "PUT_MEASUREMENT";
export const PUT_MEASUREMENT_SUCCESS = "PUT_MEASUREMENT_SUCCESS";
export const PUT_MEASUREMENT_FAIL = "PUT_MEASUREMENT_FAIL";

export const DELETE_MEASUREMENT = "DELETE_MEASUREMENT";
export const DELETE_MEASUREMENT_SUCCESS = "DELETE_MEASUREMENT_SUCCESS";
export const DELETE_MEASUREMENT_FAIL = "DELETE_MEASUREMENT_FAIL";
